# Generated by Django 2.2 on 2019-05-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_User',
        ),
    ]
